name: Test

on: [push, pull_request]

jobs:
  test:
    # continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.4","2.7", "3.2"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "bundle install"
      - run: "bundle exec rspec"
